#!/bin/bash

# Get the version number from package.json
VERSION=$(node -p "require('./package.json').version")

# Get the license text
LICENSE=$(cat LICENSE)

# Get all the contents of all the files in src/, contatenated togehter
LIB_CODE=$(cat src/lib/*.js)
MAIN_CODE=$(cat src/main.js)

for f in config/*.json; do
  filename=$(basename "$f")
  ENV="${filename%.*}"
  FILENAME="ai2html-$ENV.jsx"

  CONFIG=$(cat $f)

  echo Building $FILENAME...

  cat > $FILENAME <<_EOF_
// $FILENAME
// This is a generated file. Do not edit it manually.

/*
$LICENSE
*/

// Enclosing scripts in a named function (and not an anonymous, self-executing
// function) has been recommended as a way to minimise intermittent "MRAP" errors.
// (This advice may be superstitious, need more evidence to decide.)
// See (for example) https://forums.adobe.com/thread/1810764 and
// http://wwwimages.adobe.com/content/dam/Adobe/en/devnet/pdf/illustrator/scripting/Readme.txt
function main() {
var scriptVersion = "$VERSION";
var scriptEnvironment = "$ENV";

// ================================================
// ai2html and config settings
// ================================================

// Settings can be generated by making a copy of this Google Spreadsheet:
// https://docs.google.com/spreadsheets/d/13ESQ9ktfkdzFq78FkWLGaZr2s3lNbv2cN25F2pYf5XM/edit?usp=sharing
// Make a copy of the spreadsheet for yourself.
// Modify the settings to taste.
// Save the new data in a json file in config/.
// Run the build script.
var defaultBaseSettings = $CONFIG;
defaultBaseSettings.ai2html_environment.defaultValue = env;
defaultBaseSettings.settings_version.defaultValue = scriptVersion;

$LIB_CODE

$MAIN_CODE

} // end main() function definition
main();
_EOF_

done
